.TH simeis-server 1 "July 2025" "1.0.0" "Simeis Manual"
.SH NAME
simeis-server \- serveur du projet Simeis
.SH SYNOPSIS
.B simeis-server
[options]
.SH DESCRIPTION
Simeis-server est le serveur principal du projet Simeis.
Il permet de gérer les fonctionnalités du jeu et d'interagir avec les clients.
.SH AUTHOR
Valentin-Droid <valentin@example.com>
.SH SEE ALSO
Le projet Simeis sur GitHub.
