name: Functional Heavy Tests

on:
    workflow_dispatch:
    release:
        types: [published]

jobs:
    functional-tests:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3

            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                  python-version: '3.11'

            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip

            - name: Build and start simeis-server
              run: |
                  cargo build --release --manifest-path simeis-server/Cargo.toml
                  nohup ./target/release/simeis-server > server.log 2>&1 &
                  for i in {1..30}; do
                    if curl -s http://localhost:8000/ping | grep -q 'pong'; then
                      echo "Server is up!"
                      break
                    fi
                    echo "Waiting for server..."
                    sleep 1
                  done

            - name: Run functional tests
              run: |
                  python -m unittest discover -s example -p 'test_*.py'
