name: Functional Heavy Tests

on:
    workflow_dispatch:
    release:
        types: [published]

jobs:
    functional-tests:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              run: |
                  git clone ${{ github.server_url }}/${{ github.repository }} .
                  git fetch --all

            - name: Set up Python 3.12
              run: |
                  sudo apt-get update
                  sudo apt-get install -y python3.12 python3.12-venv python3.12-distutils
                  python3.12 -m pip install --upgrade pip

            - name: Build and start simeis-server
              run: |
                  cargo build --release --manifest-path simeis-server/Cargo.toml
                  nohup ./target/release/simeis-server &
                  sleep 10

            - name: Run functional tests
              run: |
                  python3.12 -m unittest discover -s example -p 'test_*.py'
