name: PR Target Release Branch Validation

on:
    pull_request:
        types: [opened, synchronize, reopened]

jobs:
    validate-pr-source:
        runs-on: ubuntu-latest
        steps:
            - name: Check PR source and target branches
              uses: actions/github-script@v7
              with:
                  script: |
                      const target = context.payload.pull_request.base.ref;
                      const source = context.payload.pull_request.head.ref;
                      const pr_number = context.payload.pull_request.number;
                      const validSource = source === 'main' || source.startsWith('bug/');
                      if (target.startsWith('release/') && !validSource) {
                        await github.issues.createComment({
                          ...context.repo,
                          issue_number: pr_number,
                          body: 'This PR targets a release branch but the source branch is not `main` or `bug/x`. Closing PR.'
                        });
                        await github.pulls.update({
                          ...context.repo,
                          pull_number: pr_number,
                          state: 'closed'
                        });
                        core.setFailed('Invalid source branch for release PR. PR closed.');
                      } else {
                        console.log('PR source/target branch combination is valid.');
                      }
